spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/disanayakaOilCenterDb
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
server.port=8081
