spring.application.name=demo
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://oilshop.mysql.database.azure.com:3306/disanayakaoilCenterdb?sslMode=REQUIRED}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:Oilshopdb_12_2026}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:oilshop12#@}
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8081}